spring:
  application:
    name: GETWAY-SERVICE
  cloud:    gateway:      routes:      - id: culturalactivities-service
        uri: lb://CULTURALACTIVITY-SERVICE
        predicates:        - Path=/activites/**
      - id: books-service
        uri: lb://PRETBOOK-SERVICE
        predicates:
        - Path=/books/**
              
      - id: pretbook-service
        uri: lb://PRETBOOK-SERVICE
        predicates:
        - Path=/adherants/**
      - id: pretbook-service
        uri: lb://PRETBOOK-SERVICE
        predicates:
        - Path=/prets/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8080